version: '3.1'

services:
  backend:
    build: .
    command: npm run build
    environment:
      NODE_ENV: production
    ports:
      - '5000:5000'
    expose:
      - '5000'
    volumes:
      - .:/home/app/appDir
      - /home/app/appDir/node_modules
